In [44]:
# 24 days 
import numpy as np
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])


In [45]:
import tensorflow as tf 
import pandas as pd

In [46]:
def MyScaler(data): # MinMaxScaling
#     print(np.min(data)) # 전체 data에서 최소값 도출 
#     print(np.min(data, axis=0)) # 열단위 최소값
#     print(np.min(data, axis=1)) # 행단위 최소값
    de = np.max(data, axis=0)-np.min(data, axis=0)
    num = data - np.min(data, axis=0)
    return num/de # 정규화가 되어진 결과값이 도출되어진다 
    
    
    

In [47]:
xy=MyScaler(xy) # 각각의 feature 에따라 분류하므로 열단위 최소값추출문을 써야한다 
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [48]:
# xy.shape # 8,5
xdata=xy[:,0:-1] # 전체행 # 맨 처음부터 마지막 에서 두번째 
xdata.shape 

(8, 4)

In [49]:
ydata=xy[:,[-1]]
ydata

array([[1.        ],
       [0.83755792],
       [0.6606331 ],
       [0.43800918],
       [0.42624401],
       [0.49276137],
       [0.18597238],
       [0.        ]])

In [50]:
x=tf.placeholder(tf.float32, shape=[None, 4])
y=tf.placeholder(tf.float32, shape=[None, 1])
w=tf.Variable(tf.random_normal([4,1])) # 종가확인 
b=tf.Variable(tf.random_normal([1]))

In [78]:
hf=tf.matmul(x,w)+b # 가설함수 예측값 
cost=tf.reduce_mean(tf.square(hf-y))
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [64]:
# optimizing process
train=tf.train.GradientDescentOptimizer(1e-3).minimize(cost)

In [65]:

sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x:xdata, y:ydata})
    print(step, 'cost:', cv, 'hf:', hv)

0 cost: 2.5357344 hf: [[2.0535269]
 [3.0783343]
 [2.3821945]
 [1.6104614]
 [1.9910088]
 [1.9753139]
 [1.5000086]
 [1.8556175]]
1 cost: 2.5180783 hf: [[2.046143 ]
 [3.0708017]
 [2.3759208]
 [1.6056044]
 [1.9852898]
 [1.9697663]
 [1.496119 ]
 [1.8516726]]
2 cost: 2.500556 hf: [[2.0387883]
 [3.0632977]
 [2.3696704]
 [1.600766 ]
 [1.9795928]
 [1.9642398]
 [1.4922438]
 [1.8477418]]
3 cost: 2.4831662 hf: [[2.031463 ]
 [3.0558224]
 [2.3634439]
 [1.5959461]
 [1.9739175]
 [1.9587345]
 [1.4883828]
 [1.8438252]]
4 cost: 2.4659083 hf: [[2.0241663]
 [3.0483751]
 [2.3572412]
 [1.5911444]
 [1.9682639]
 [1.9532502]
 [1.484536 ]
 [1.8399225]]
5 cost: 2.4487808 hf: [[2.016899 ]
 [3.0409563]
 [2.3510623]
 [1.5863612]
 [1.962632 ]
 [1.9477868]
 [1.4807034]
 [1.8360338]]
6 cost: 2.4317832 hf: [[2.0096605]
 [3.0335655]
 [2.3449063]
 [1.5815961]
 [1.9570217]
 [1.9423442]
 [1.4768848]
 [1.8321592]]
7 cost: 2.414914 hf: [[2.0024507]
 [3.026203 ]
 [2.3387742]
 [1.5768492]
 [1.9514327]
 [1.9369223]
 [1.4730804]


In [ ]:
##################### data processing ######################

In [79]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
# 4개의 feature 

#y값은 one hot 인코딩 방식으로 초기화 함...(a,b,c)중 하나를 hot하게 함...
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0
# 3개의 label 

In [80]:
num_classes=3 
x=tf.placeholder('float',[None,4])
y=tf.placeholder('float',[None,num_classes]) # 결과가 3개 ( 1, 0, 0 ) (0, 1, 0) 처럼 나온다
w=tf.Variable(tf.random_normal([4,num_classes])) 
b=tf.Variable(tf.random_normal([num_classes]))
# hf=x*w+b
# [None,4] [4, ] + [ 3 ] 

In [95]:
hf=tf.nn.softmax(tf.matmul(x,w)+b)
# sum 
# reduce_mean
# elements 들의 곱셉 
cost = tf.reduce_mean(-tf.reduce_sum(tf.log(hf),axis=1))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [98]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={x:x_data, y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={x:x_data, y:y_data}))
    print('='*50)
#xdata = 1,11,7,9 => Y ?      
    res=sess.run(hf, feed_dict={x:[[1,11,7,9]]})
    res2=sess.run(hf, feed_dict={x:[[1,11,7,9],
                                   1,3,4,3],
                                   [1,1,0,1]]})
    
    sess.run(tf.argmax(res, axis=1))
            

0 18.603128
200 3.3842392
400 3.342967
600 3.3304787
800 3.3221273
1000 3.3158226
1200 3.3110175
1400 3.3073568
1600 3.3045716
1800 3.3024547
2000 3.3008473


In [99]:
res
res2

array([[0.28664675, 0.29898617, 0.41436708],
       [0.35940397, 0.3501607 , 0.2904353 ],
       [0.36638445, 0.34468862, 0.28892693]], dtype=float32)

In [100]:
df=pd.read_csv('data/diabete/zoo.csv')
df

# https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data  \
0                    #   1. animal name:     (deleted)                         
1                             #   2. hair     Boolean"                         
2                         #   3. feathers     Boolean"                         
3                             #   4. eggs     Boolean"                         
4                             #   5. milk     Boolean"                         
5                         #   6. airborne     Boolean"                         
6                         #   7. aquatic      Boolean"                         
7                         #   8. predator     Boolean"                         
8                         #   9. toothed      Boolean"                         
9                         #  10. backbone     Boolean"                         
10                        #  11. breathes     Boolean"                         
11                        #  12. venomous     Boolean"                         
12                            #  13. fins     Boolean"                         
13         #  14. legs     Numeric (set of values: {0"                         
14                            #  15. tail     Boolean"                         
15                        #  16. domestic     Boolean"                         
16                        #  17. catsize      Boolean"                         
17   #  18. type     Numeric (integer values in ran...                         
18                                                   1                         
19                                                   1                         
20                                                   0                         
21                                                   1                         
22                                                   1                         
23                                                   1                         
24                                                   1                         
25                                                   0                         
26                                                   0                         
27                                                   1                         
28                                                   1                         
29                                                   0                         
..                                                 ...                         
89                                                   0                         
90                                                   0                         
91                                                   0                         
92                                                   1                         
93                                                   1                         
94                                                   0                         
95                                                   0                         
96                                                   0                         
97                                                   0                         
98                                                   0                         
99                                                   0                         
100                                                  0                         
101                                                  0                         
102                                                  1                         
103                                                  0                         
104                                                  0                         
105                                                  0                         
106                                                  0                         
107 

In [111]:
xy=np.loadtxt('data/diabete/zoo.csv', delimiter=',',dtype=np.float32)
xy.shape #
xdata = xy[:,0:-1]
ydata = xy[:,[-1]]

In [119]:
x=tf.placeholder(tf.float32, [None, 16])
y=tf.placeholder(tf.int32, [None, 1]) 
# ohe 는 type 이 int형이여야 실행된다
# 0-6 # 분류기는 7개 ( 종류 )
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 => 0 번 종류 동물에 대한확률 
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 => 1 번 
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 
# ....
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률  => 6번 
# 1000000, 0100000,... => [None, 7]

In [120]:
# tf ) ohe 함수 따로 존재
y_one_hot=tf.one_hot(y, 7) # 동물번호 : 3 -> 0001000 < ohe >
print('one_hot', y_one_hot)
y_one_hot=tf.reshape(y_one_hot, [-1,7])
print('one_hot after reshape', y_one_hot)
# ohe hot 함수는 한 차원 높게 변환됨 
# y : [[0],[3], .... [5]]] => [None,1] shape
# one_hot = > [[[1000000]], [[0001000],,,,[00000100]]] => [None, 1, 7]
# 우리가 바라는 출력 결과의 모습은 ( shape ) = [None,7]
# reshape을 하면됨 tf.shape(y_one_hot, [-1,7 ]) 코딩하면 
# [None, 7] 로 reshape됨
# [[[1000000]], [[001]]]


one_hot Tensor("one_hot_4:0", shape=(?, 1, 7), dtype=float32)
one_hot after reshape Tensor("Reshape_3:0", shape=(?, 7), dtype=float32)


In [135]:
w=tf.Variable(tf.random_normal([16, 7]))
b=tf.Variable(tf.random_normal([7]))
#x:[None,16], w:[16,7]
logit= tf.matmul(x,w)+b
hf=tf.nn.softmax(logit)
cost=tf.nn.softmax_cross_entropy_with_logits(logits=logit,
                                             labels=y_one_hot)
cost2=tf.reduce_mean(cost)
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost2)
prediction=tf.argmax(hf,1)
correct_prediction= tf.equal(prediction,tf.argmax(y_one_hot,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


In [136]:
# with tf.Session() as sess:
#         sess.run(tf.global_variables_initializer())

#         for step in range(10001):
             
#             sess.run(train, feed_dict = {x:xdata, y:ydata})
#             if step % 100 == 0:
#                 cv = sess.run([cost, hf, train], feed_dict = {x:xdata, y:ydata})
#                     print('step:', step, 'cost:',cv)

In [146]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x:xdata, y:ydata})
        if step % 100==0:
            cv, av=sess.run([cost2, accuracy], feed_dict={x:xdata, y:ydata})
            print("step:", step, "cost:",cv, "acc:", av)
#전체 데이터로 트레이닝 수행하여 모델 생성
#모델에 전체 데이터를 집어 넣어서 정확도 출력
#데이터를 분할하지 않았음
    pred=sess.run(prediction, feed_dict={x:xdata})
    for p,y in zip(pred, ydata.flatten()):
        print('[{}] 예측: {} 실제 y:{}'.format(p==int(y), p, int(y)))
            
#     print(pred)


TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a float32 into a Tensor.

In [ ]:
# zip 함수 : 끼리끼리 묶어주는 함수 
# flatten 
# [[1],[0]] => [1,0]
