In [1]:
print("hello")

hello


# 마크다운 
## 반갑습니다
### 안녕하세요
#### 결혼축하드려요 윤기형님

In [2]:
import numpy as np

In [3]:
x=np.arange(1,10001)
x2=np.arange(10001,20001)

In [7]:
%%time

x3=np.zeros_like(x)
for i in range(10000):
    x3[i]=x[i]+x2[i]

Wall time: 4.99 ms


In [5]:
%%time
x3=x+x2

Wall time: 0 ns


In [6]:
np.exp(1)

2.718281828459045

In [8]:
np.exp(2)

7.38905609893065

In [11]:
x=np.array([4,5,6,7])
print(x.argmin()) 
print(x.argmax())

0
3


In [12]:
x=np.array([[1, 2],
           [3, 4],
           [5, 6]])

In [13]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
x.sum()
x.sum(axis=0) # 0 이면 열단위로
x.sum(axis=1) # 1 이면 행단위로

array([ 3,  7, 11])

In [16]:
x=np.array([[11,2],[23,14],[5,26]])
print(np.sort(x)) # axis = 1로 줬을때와 동일
print("*"*50)
print(np.sort(x,axis=0))

[[ 2 11]
 [14 23]
 [ 5 26]]
**************************************************
[[ 5  2]
 [11 14]
 [23 26]]


In [17]:
x

array([[11,  2],
       [23, 14],
       [ 5, 26]])

In [18]:
x=np.array([40,30,10,20])
np.argsort(x)
#  0  1  2  3       2  3  1  0
#[40,30,10,20] => [10,20,30,40]

array([2, 3, 1, 0], dtype=int64)