In [ ]:
# day 19
# 순전파 / 역전파 배열 진행양상 # day18_

In [1]:
import numpy as np
import pandas as pd
from jupyterthemes import jtplot
jtplot.style(theme='gruvboxd', context='paper', spines=True, 
             ticks=True, grid=True, gridlines='dotted', figsize=(6,4.5))


In [22]:
# 생성자 함수 
# class : 함수와 변수로 구성되어진것 
# 붕어빵기계틀 (클래스) 만들어주기 class // 내용물과 같은 특성과 동작으로 이루어짐 

class MulLayer: 
    def __init__(self):
        self.x=None #(self = this [기타언어])
        self.y=None # (붕어빵의 규모 설정)

    def forward(self,x,y):
        self.x=x
        self.y=y
        out=x*y
        return out
    def backward(self, dout, ): # dout : 1 # self_y : 1.1
        dx = dout*self.y
        dy = dout*self.x # 역접 
        return(dx,dy)


In [23]:
# 결과값 동일하게 도출
# def forward(x, y):
#     out=x*y
#     return out

# 객체 생성 
# 붕어빵 (객체) 만들어주기 by[class뒤에 괄호]
mal=MulLayer()
mtl=MulLayer()    
# 붕어빵 두개 만들기

In [24]:
# 정전파 계산 ( forward profagation )
# mal -> mtl

apple = 100
apple_num = 2 
tax = 1.1
apple_price=mal.forward(apple, apple_num) # 객체. 메서드명 => 생성
price=mtl.forward(apple_price, tax) # 각 각 x,y 자리에 대입되어짐 // 객체에 저장 
print('price :', int(price)) # back profagation에 적용시키기 위해 동적할당 가능 객체생성

####### 지금껏 순전파 ########

price : 220


In [27]:
# mtl -> mal

dprice = 1
dapple_price, dtax = mtl.backward(dprice)
# print((dapple_price, dtax))
dapple, dapple_num = mal.backward(dapple_price)
print(dapple, dapple_num, dtax)

####### 지금껏 역전파 ########

2.2 110.00000000000001 200


In [3]:
## TensorFlow ##
# 상수형 (Constant)
import tensorflow as tf

In [35]:
a = tf.constant([5]. dtype=tf.float32)
# b = tf.constant([10], dtype=tf.float32)
# c = tf.constant([2], dtype=tf.float32)
# # 5가 나와야하는데 실행값이 의외의값이 나옴
# # node에 대한 정보가 도출됨 
# d = a * b + c
# d # <= 변수라고 호칭하지않고, a.k.a '상수' // 'node명' 이다
# ( 연산 : 보관(항등함수) , 저장 , ) 기능하는것 = node
# 그러므로 a = [5] => 해당 노드를 가리킴 (node or edge) [=뉴런]
# edge : 다차원 배열 (value) 값
# tf.variable : 진정한 변수 

# tensor(가중치) // flow  => neuron Network
# node 해당 layer 요소 
# graph는 노드와 엣지로 구성




In [34]:
# session을 생성해서 그래프 실행 
# 세션 : 그래프를 실행시켜주는 runner
# tensor 내에 Session 이란 class가 존재

sess = tf.Session()
# sess : 노드, 
sess.run(a) # a노드를 실행 해주세욤 // # array객체 도출
# [5.] # 플롯으로 도출됨 
 


array([5.], dtype=float32)

In [36]:
# 플레이스 홀더 ( Place Holder ) // 학습고자 하는 train data 전달 받기용 저장소 

# 그래프 실행 시키는 이유  : 궁극적 목표, 모델만들기 
# 모델 만드는 행위 | training 시킨다 
# x [1, 2, 3]
# [2, 4, 6]

In [41]:
data = [1,2,3,4]
x = tf.placeholder(dtype=tf.float32)
y = x * 2 # [노드]
# -------------------- 그래프 -------------------------
print(sess.run(y, feed_dict={x:data})) # 그래프 실행 # y라는 노드 실행 # 역으로 올라간다 
# feed_dict : 딕셔너리형태로 학습용 데이터를 전달해줘라 # [뒤에서부터 실행되는 느낌]
# { key : value }
# {x( 전달받을 0) : [1,2,3,4]}
# broadcasting 
# feeding(값을전달하는것) 해줘야함 .. 방법 : 학습용 데이터를 전달하는 행위 
# 그래프 실행 시점에 피딩이 있어야한다!!!!! 


[2. 4. 6. 8.]


In [44]:
# 변수 (variable)
# : 훈련(training, modeling)과정에서 변화하는 기울기, 절편 등 => 변수 

# hf = wx+b
# Hypersis Func

In [49]:
inputData = [1,2,3]
x = tf.placeholder(dtype = tf.float32)
w = tf.Variable([2], dtype = tf.float32)
yhat = w * x

sess = tf.Session() # 세션객체 생성
'''
init=  tf
'''
sess.run(tf.global_variables_initializer()) # 변수 초기화 => session객체 생성후에 가능 
sess.run(yhat, feed_dict={x:inputData})


array([2., 4., 6.], dtype=float32)

In [62]:
# tf.matmul( , ) 활요
# 행렬의 곱셈을 하는 함수 
# Matrix Multiplier 
x = tf.constant([[1,2,3]])
# w = tf.constant([2,2,2])
w = tf.constant([[2],[2],[2]])
y = tf.matmul(x,w)
sess.run(y)
# rank : 차원 // error : 1차원으로는 안돼! 2차원 [matrix] 형태로 던져줘



array([[12]])

In [63]:
x = tf.constant([[1,2,3]])
w = tf.constant([[2],[2],[2]])
y = tf.matmul(x,w)
print(sess.run(y)[0][0])


12


In [64]:
x = tf.Variable([[1,2,3]])
w = tf.constant([[2],[2],[2]])
y = tf.matmul(x,w)
init=tf.global_variables_initializer()
sess.run(init)
sess.run(y)

array([[12]])

In [58]:
# 번외 내코드 ㅋ
a=np.dot((1,2,3),(2,2,2))
a

12

In [65]:
x = tf.Variable([[1,2,3],[1,2,3],[2,3,4]])
w = tf.constant([[2],[2],[2]])
y = tf.matmul(x,w)
init=tf.global_variables_initializer()
sess.run(init)
sess.run(y)


array([[12],
       [12],
       [18]])

In [66]:
# None : 아직 결정되지 않은 상태 
indata=[[1,2,3],[1,2,3],[2,3,4]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3]) # 행부분은 아직 결정된게없다->자동배치
w=tf.constant([[2],[2],[2]], dtype=tf.float32)
y=tf.matmul(x,w) # 3*3 , 3*1 = 3*1 
init=tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:indata}) # 3행3열

# 학습할때마다 데이터 량이 달라질수 있으므로 shape부분 행부분 특정값을 고정시키지 않고 
# None값으로 할당시켜둔다

array([[12],
       [12],
       [18]])

In [68]:
data=[[1,1,1],[2,2,2]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3]) 
w=tf.Variable([[2],[2],[2]], dtype=tf.float32)
b=tf.Variable([4], dtype=tf.float32) 
y = tf.matmul(x,w)+b # 2*3 3*1 => 2*1
# 1 1 1  2
# 2 2 2  2  => 6+4 = 10
#        2  => 12+4 = 16
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)