In [1]:
# day21 
# multi-variable
import pandas as pd
import tensorflow as tf
# house = pd.read_csv('data/house/train.csv')
# house

In [2]:
import numpy as np
# house.columns

In [3]:
# IM = house[['Id', 'MSSubClass']]
# IM

In [4]:
x1data = [70, 90, 88, 95, 75] # 3월 모의고사
x2data = [80, 88, 90, 98, 65] # 4월 모의고사
x3data = [75, 93, 90, 100, 70] # 5월 모의고사
ydata = [150, 185, 180, 200, 140] # 수능점수

# 예측값[149.75005 185.1799180.01122 198.90154 141.55467

In [5]:
# x,y
x1=tf.placeholder(dtype=tf.float32)
x2=tf.placeholder(dtype=tf.float32)
x3=tf.placeholder(dtype=tf.float32)

#################### 모의고사 ############################
y=tf.placeholder(tf.float32) #수능 점수

# w, b 
w1=tf.Variable(tf.random_normal([1]), name='weight1')
w2=tf.Variable(tf.random_normal([1]), name='weight2')
w3=tf.Variable(tf.random_normal([1]), name='weight3')
b=tf.Variable(tf.random_normal([1]), name='bias')

# 가설함수
hf=x1*w1 + x2*w2 + x3*w3 + b
cost=tf.reduce_mean(tf.square(hf-y))

# traindata
temp=tf.train.GradientDescentOptimizer(1e-5)
train=temp.minimize(cost)
sess=tf.Session()
sess.run(tf.global_variables_initializer())


In [6]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train],
    feed_dict={x1:x1data, x2:x2data, x3:x3data, y:ydata})
    if step % 10 == 0:
        print(step,'cost:',cv,'prediction', hv)


0 cost: 19.413536 prediction [155.0922  178.1966  180.71747 195.22652 138.755  ]
10 cost: 16.486263 prediction [156.56853 179.9975  182.4905  197.1658  140.15968]
20 cost: 16.43855 prediction [156.55922 180.00899 182.4941  197.17035 140.17822]
30 cost: 16.391153 prediction [156.54501 180.01453 182.49182 197.16847 140.19208]
40 cost: 16.344065 prediction [156.53079 180.01996 182.4895  197.16658 140.20584]
50 cost: 16.297405 prediction [156.51668 180.02542 182.48721 197.16467 140.21953]
60 cost: 16.251001 prediction [156.5026  180.03084 182.4849  197.16281 140.23317]
70 cost: 16.205036 prediction [156.48859 180.03624 182.4826  197.16093 140.24675]
80 cost: 16.159332 prediction [156.47462 180.04164 182.48032 197.15907 140.26025]
90 cost: 16.113964 prediction [156.46071 180.04701 182.47803 197.15721 140.2737 ]
100 cost: 16.068909 prediction [156.44685 180.05238 182.47578 197.1554  140.28711]
110 cost: 16.024178 prediction [156.43306 180.05774 182.47353 197.15358 140.30042]
120 cost: 15.979

1320 cost: 12.363066 prediction [155.10658 180.59491 182.24435 197.00606 141.52725]
1330 cost: 12.343109 prediction [155.09799 180.59857 182.24275 197.00531 141.53471]
1340 cost: 12.323263 prediction [155.08945 180.60225 182.2412  197.0046  141.54214]
1350 cost: 12.303513 prediction [155.08093 180.6059  182.2396  197.00389 141.54955]
1360 cost: 12.283868 prediction [155.07246 180.60956 182.23802 197.0032  141.5569 ]
1370 cost: 12.264344 prediction [155.064   180.61319 182.23647 197.0025  141.56422]
1380 cost: 12.244967 prediction [155.05562 180.61684 182.23492 197.00186 141.57153]
1390 cost: 12.225658 prediction [155.04721 180.62045 182.23337 197.00116 141.57878]
1400 cost: 12.206446 prediction [155.03885 180.62405 182.2318  197.00049 141.58598]
1410 cost: 12.187384 prediction [155.03052 180.62764 182.23026 196.99982 141.59315]
1420 cost: 12.168382 prediction [155.02223 180.63124 182.2287  196.99918 141.60031]
1430 cost: 12.149569 prediction [155.01398 180.63481 182.22716 196.9985  141

In [7]:
#행렬로 데이터 표현
xdata=[[70, 90, 88, 95, 75],
[80, 88, 90, 98, 65],
[75, 93, 90, 100, 70]]#5월 모의고사
ydata=[150, 185, 180, 200, 140] #수능점수


In [8]:
np.shape(xdata)
xdata=np.transpose(xdata)
np.shape(xdata)

ydata=[[150],[185],[180],[200], [140]]
np.shape(ydata)


(5, 1)

In [9]:
x=tf.placeholder(tf.float32,shape=[None,3])
y=tf.placeholder(tf.float32,shape=[None,1])
w=tf.Variable(tf.random_normal([3,1]), name='weight')
b=tf.Variable(tf.random_normal([1]), name='bias')

In [13]:
# hf=x*w+b # 이제 이렇게 쓰면 앙대여
hf = tf.matmul(x,w)+b
cost = tf.reduce_mean(tf.square(hf-y))
train=tf.train.GradientDescentOptimizer(1e-5).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train],
                         feed_dict = {x:xdata,y:ydata})
    if step % 10==0:
        print(step, "cost:",cv,"prediction:",hv)


0 cost: 28005.512 prediction: [[ 9.509052 ]
 [ 3.6587753]
 [ 6.237526 ]
 [ 6.8351517]
 [-1.064396 ]]
10 cost: 16.111273 prediction: [[156.46509]
 [180.6858 ]
 [181.27875]
 [198.22884]
 [136.07896]]
20 cost: 15.695445 prediction: [[156.93489]
 [181.28488]
 [181.86089]
 [198.86464]
 [136.56046]]
30 cost: 15.593312 prediction: [[156.91512]
 [181.29413]
 [181.85985]
 [198.8628 ]
 [136.58504]]
40 cost: 15.492044 prediction: [[156.89378]
 [181.30136]
 [181.85687]
 [198.85881]
 [136.60799]]
50 cost: 15.39162 prediction: [[156.87253]
 [181.30858]
 [181.85387]
 [198.85483]
 [136.63078]]
60 cost: 15.292036 prediction: [[156.85138]
 [181.31577]
 [181.85092]
 [198.85089]
 [136.65353]]
70 cost: 15.193286 prediction: [[156.8303 ]
 [181.3229 ]
 [181.84795]
 [198.84695]
 [136.67616]]
80 cost: 15.09534 prediction: [[156.80931]
 [181.33003]
 [181.84499]
 [198.84303]
 [136.69867]]
90 cost: 14.99823 prediction: [[156.78842]
 [181.33713]
 [181.84206]
 [198.83914]
 [136.72112]]
100 cost: 14.901906 predictio

1280 cost: 7.677842 prediction: [[154.82895]
 [182.01671]
 [181.55939]
 [198.49031]
 [138.79187]]
1290 cost: 7.6416464 prediction: [[154.81622]
 [182.02126]
 [181.55751]
 [198.48819]
 [138.80505]]
1300 cost: 7.6057 prediction: [[154.80353]
 [182.02577]
 [181.5556 ]
 [198.48608]
 [138.81816]]
1310 cost: 7.570089 prediction: [[154.7909 ]
 [182.03026]
 [181.55371]
 [198.48398]
 [138.8312 ]]
1320 cost: 7.5347357 prediction: [[154.77834]
 [182.03477]
 [181.55183]
 [198.4819 ]
 [138.84422]]
1330 cost: 7.4996805 prediction: [[154.76581]
 [182.03926]
 [181.54997]
 [198.47981]
 [138.85715]]
1340 cost: 7.464864 prediction: [[154.75331]
 [182.04372]
 [181.54811]
 [198.47774]
 [138.87004]]
1350 cost: 7.430381 prediction: [[154.74089]
 [182.04814]
 [181.54623]
 [198.4757 ]
 [138.88284]]
1360 cost: 7.39618 prediction: [[154.72852]
 [182.05257]
 [181.54439]
 [198.47362]
 [138.8956 ]]
1370 cost: 7.3622103 prediction: [[154.71622]
 [182.057  ]
 [181.54256]
 [198.47163]
 [138.90833]]
1380 cost: 7.328547

In [14]:
stock=pd.read_csv('data/stock_daily.csv')
# stock

In [15]:
xy=np.loadtxt('data/test-score.csv', delimiter=',', dtype=np.float32)
xy
# xdata : 1-3열, ydata : 4열 
# 100, 70, 102 => 예상
# 60, 70, 100 => 예상
# 80, 90, 95 => 예상
# cost 출력 


array([[ 80.,  79.,  77., 149.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [18]:
# 오혁형님 문제 해결풀이 코드 

import matplotlib.pyplot as plt
from tensorflow import keras
import tensorflow as tf
import numpy as np
import pandas as pd
 
print(tf.__version__)
 
data = np.loadtxt("data/test-score.csv",delimiter = ',', dtype = np.float32)
 
xdata = data[:,0:3]
ydata = data[:,3].reshape(-1,1)
 
x = tf.placeholder(tf.float32, shape = (None, 3))
y = tf.placeholder(tf.float32, shape = (None, 1))
 
w = tf.Variable(tf.random.normal([3,1]), name = "weight")
b = tf.Variable(tf.random.normal([1]), name = 'bias')
 
hf = x @ w + b
cost = tf.reduce_mean(tf.square(hf - y)) 
 
train = tf.train.GradientDescentOptimizer(1e-5).minimize(cost)
 
sess = tf.Session()
sess.run(tf.global_variables_initializer())
 
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x : xdata , y : ydata})
    
    if step == 2000:
        print(step, "cost : ", cv, "prediction : ", hv)
 
test = np.transpose([[100, 70, 102],#142
                     [60, 70, 100], #162
                     [80, 90, 95] ]) #195
 
for data in test:
    print(sess.run(hf, feed_dict = {x : data.reshape(-1,3) }))

1.14.0
2000 cost :  8.472928 prediction :  [[156.40796 ]
 [183.90234 ]
 [181.21646 ]
 [198.97742 ]
 [138.64731 ]
 [104.201546]
 [150.97415 ]
 [114.88515 ]
 [173.56879 ]
 [163.99416 ]
 [143.76813 ]
 [142.18788 ]
 [185.70352 ]
 [151.98322 ]
 [151.79578 ]
 [188.10593 ]
 [142.75465 ]
 [182.45078 ]
 [176.79172 ]
 [158.36774 ]
 [176.66684 ]
 [173.94809 ]
 [167.97606 ]
 [150.71942 ]
 [189.96988 ]]
[[153.02377]]
[[164.40683]]
[[195.49944]]


In [21]:

from sklearn.model_selection import train_test_split
x,y = np.arange(10).reshape((5,2)), range(5)
list(y)
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.33, random_state=42)
print(xtrain)
print(xtest)
x = np.array([[10., -10., 1],
             [5., 0., 2.],
             [15., 10., 22.]])


[[4 5]
 [0 1]
 [6 7]]
[[2 3]
 [8 9]]


In [26]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit_transform(x)
scaler.transform(x)

QUEUE_LENGTH=20
q=tf.FIFOQueue(QUEUE_LENGTH, 'float')
enq_ops = q.enqueue_many(([1.0, 2.0, 3.0, 4.0],))
qr=tf.train.QueueRunner(q, [enq_ops, enq_ops, enq_ops])



W0730 16:25:17.833774 14764 deprecation.py:323] From <ipython-input-26-f3529137a414>:10: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [29]:
sess=tf.Session()
coord=tf.train.Coordinator()
threads=qr.create_threads(sess, coord=coord, start=True)

for step in range(30):
    print(sess.run(q.dequeue()))

coord.request_stop() #스레드 정지
coord.join(threads) #정지될때까지 기다리는 함수

1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0


In [31]:
QUEUE_LENGTH=20
q=tf.FIFOQueue(QUEUE_LENGTH, "float")
enq_ops1=q.enqueue_many(([1.0,2.0,3.0,4.0],))
enq_ops2=q.enqueue_many(([5.0,6.0,7.0,8.0],))
enq_ops3=q.enqueue_many(([9.0,10.0,11.0,12.0],))
qr=tf.train.QueueRunner(q, [enq_ops1, enq_ops2, enq_ops3])

In [33]:
sess=tf.Session()
coord=tf.train.Coordinator()
threads=qr.create_threads(sess, coord=coord, start=True)

for step in range(30):
    print(sess.run(q.dequeue()))

coord.request_stop() #스레드 정지
coord.join(threads) #정지될때까지 기다리는 함수

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
9.0
10.0
11.0
12.0
5.0
6.0
7.0
8.0
1.0
2.0


In [34]:
# 파일에서 데이터 읽기 작업순서
# 1. 파일 목록 읽기
# 2. 파일목록을 파일이름큐에 저장 
# 3. reader가 파일이름큐에서 파일명을 하나씩 읽어온다 
# 4. decoder는 파일에 있는 데이터를 읽어들인다
# 5. 데이터 정제 (전처리)
# 6. 정제된 데이터를 example queue에 저장
# 7. 학습진행 
# multi thread


In [ ]:
queue=tf.train.string_input_producer(['q_1.txt','q_2.txt','q_3.txt'], shuffle=False)
coord=tf.train.Coordinator()
sess=tf.Session()
reader=tf.TextLineReader()
key, value = reader.read(queue=queue)
print(key)
print(value)
print(sess.run(key))
print(sess.run(value))



W0730 16:26:14.279830 14764 deprecation.py:323] From <ipython-input-35-33a0715ef189>:1: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0730 16:26:14.285814 14764 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0730 16:26:14.286811 

Tensor("ReaderReadV2:0", shape=(), dtype=string)
Tensor("ReaderReadV2:1", shape=(), dtype=string)


In [ ]:
for i in range(100):
    speed, distance = tf.decode_csv(value, record_defaults=[[0],[0]]) 
    # 결측치에 대한 초기값 지정
#     print(sess.run([speed, distance]))
coord.request_stop() # 스레드 정지 
coord.join(threads)
    