In [16]:
# 24 days 
import numpy as np
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])


In [17]:
import tensorflow as tf 
import pandas as pd

In [18]:
def MyScaler(data): # MinMaxScaling
#     print(np.min(data)) # 전체 data에서 최소값 도출 
#     print(np.min(data, axis=0)) # 열단위 최소값
#     print(np.min(data, axis=1)) # 행단위 최소값
    de = np.max(data, axis=0)-np.min(data, axis=0)
    num = data - np.min(data, axis=0)
    return num/de # 정규화가 되어진 결과값이 도출되어진다 
    
    
    

In [19]:
xy=MyScaler(xy) # 각각의 feature 에따라 분류하므로 열단위 최소값추출문을 써야한다 
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [20]:
# xy.shape # 8,5
xdata=xy[:,0:-1] # 전체행 # 맨 처음부터 마지막 에서 두번째 
xdata.shape 

(8, 4)

In [21]:
ydata=xy[:,[-1]]
ydata

array([[1.        ],
       [0.83755792],
       [0.6606331 ],
       [0.43800918],
       [0.42624401],
       [0.49276137],
       [0.18597238],
       [0.        ]])

In [22]:
x=tf.placeholder(tf.float32, shape=[None, 4])
y=tf.placeholder(tf.float32, shape=[None, 1])
w=tf.Variable(tf.random_normal([4,1])) # 종가확인 
b=tf.Variable(tf.random_normal([1]))

In [23]:
hf=tf.matmul(x,w)+b # 가설함수 예측값 
cost=tf.reduce_mean(tf.square(hf-y))
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [24]:
# optimizing process
train=tf.train.GradientDescentOptimizer(1e-3).minimize(cost)

In [25]:

sess=tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x:xdata, y:ydata})
    print(step, 'cost:', cv, 'hf:', hv)

0 cost: 0.52980936 hf: [[ 0.5146752 ]
 [-0.19630325]
 [-0.19004518]
 [-0.18983197]
 [-0.1254198 ]
 [-0.18710801]
 [-0.50945675]
 [-0.7523637 ]]
1 cost: 0.52611715 hf: [[ 0.5180563 ]
 [-0.19286144]
 [-0.1871765 ]
 [-0.18760884]
 [-0.12280321]
 [-0.18457037]
 [-0.5076773 ]
 [-0.75056213]]
2 cost: 0.5224529 hf: [[ 0.5214241 ]
 [-0.18943268]
 [-0.18431878]
 [-0.18539417]
 [-0.12019667]
 [-0.1820423 ]
 [-0.50590444]
 [-0.7487671 ]]
3 cost: 0.5188164 hf: [[ 0.5247784 ]
 [-0.186017  ]
 [-0.18147188]
 [-0.18318802]
 [-0.11760014]
 [-0.179524  ]
 [-0.5041381 ]
 [-0.74697846]]
4 cost: 0.5152075 hf: [[ 0.5281195 ]
 [-0.18261433]
 [-0.17863584]
 [-0.18099025]
 [-0.11501351]
 [-0.1770153 ]
 [-0.50237834]
 [-0.74519634]]
5 cost: 0.5116258 hf: [[ 0.5314474 ]
 [-0.17922446]
 [-0.17581052]
 [-0.17880079]
 [-0.11243674]
 [-0.17451608]
 [-0.50062495]
 [-0.7434205 ]]
6 cost: 0.5080713 hf: [[ 0.53476197]
 [-0.17584756]
 [-0.17299601]
 [-0.17661971]
 [-0.10986987]
 [-0.17202646]
 [-0.49887806]
 [-0.74165106

In [26]:
##################### data processing ######################

In [27]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
# 4개의 feature 

#y값은 one hot 인코딩 방식으로 초기화 함...(a,b,c)중 하나를 hot하게 함...
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0
# 3개의 label 

In [28]:
num_classes=3 
x=tf.placeholder('float',[None,4])
y=tf.placeholder('float',[None,num_classes]) # 결과가 3개 ( 1, 0, 0 ) (0, 1, 0) 처럼 나온다
w=tf.Variable(tf.random_normal([4,num_classes])) 
b=tf.Variable(tf.random_normal([num_classes]))
# hf=x*w+b
# [None,4] [4, ] + [ 3 ] 

In [29]:
hf=tf.nn.softmax(tf.matmul(x,w)+b)
# sum 
# reduce_mean
# elements 들의 곱셉 
cost = tf.reduce_mean(-tf.reduce_sum(tf.log(hf),axis=1))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [32]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={x:x_data, y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={x:x_data, y:y_data}))
    print('='*50)
#xdata = 1,11,7,9 => Y ?      
    res=sess.run(hf, feed_dict={x:[[1,11,7,9]]})
    res2=sess.run(hf, feed_dict={x:[[1,11,7,9],
                                   [1,3,4,3],
                                   [1,1,0,1]]})
    
    sess.run(tf.argmax(res, axis=1))
            

0 22.707104
200 3.4429479
400 3.3496587
600 3.328915
800 3.3174882
1000 3.310258
1200 3.3055847
1400 3.3025217
1600 3.3004858
1800 3.2991114
2000 3.2981703


In [33]:
res
res2

array([[0.38789245, 0.30617747, 0.3059301 ],
       [0.30533472, 0.34484586, 0.34981945],
       [0.31969377, 0.30782503, 0.37248117]], dtype=float32)

In [34]:
df=pd.read_csv('data/diabete/zoo.csv')
df

# https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data  \
0                    #   1. animal name:     (deleted)                         
1                             #   2. hair     Boolean"                         
2                         #   3. feathers     Boolean"                         
3                             #   4. eggs     Boolean"                         
4                             #   5. milk     Boolean"                         
5                         #   6. airborne     Boolean"                         
6                         #   7. aquatic      Boolean"                         
7                         #   8. predator     Boolean"                         
8                         #   9. toothed      Boolean"                         
9                         #  10. backbone     Boolean"                         
10                        #  11. breathes     Boolean"                         
11                        #  12. venomous     Boolean"                         
12                            #  13. fins     Boolean"                         
13         #  14. legs     Numeric (set of values: {0"                         
14                            #  15. tail     Boolean"                         
15                        #  16. domestic     Boolean"                         
16                        #  17. catsize      Boolean"                         
17   #  18. type     Numeric (integer values in ran...                         
18                                                   1                         
19                                                   1                         
20                                                   0                         
21                                                   1                         
22                                                   1                         
23                                                   1                         
24                                                   1                         
25                                                   0                         
26                                                   0                         
27                                                   1                         
28                                                   1                         
29                                                   0                         
..                                                 ...                         
89                                                   0                         
90                                                   0                         
91                                                   0                         
92                                                   1                         
93                                                   1                         
94                                                   0                         
95                                                   0                         
96                                                   0                         
97                                                   0                         
98                                                   0                         
99                                                   0                         
100                                                  0                         
101                                                  0                         
102                                                  1                         
103                                                  0                         
104                                                  0                         
105                                                  0                         
106                                                  0                         
107 

In [35]:
xy=np.loadtxt('data/diabete/zoo.csv', delimiter=',',dtype=np.float32)
xy.shape #
xdata = xy[:,0:-1]
ydata = xy[:,[-1]]

In [36]:
x=tf.placeholder(tf.float32, [None, 16])
y=tf.placeholder(tf.int32, [None, 1]) 
# ohe 는 type 이 int형이여야 실행된다
# 0-6 # 분류기는 7개 ( 종류 )
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 => 0 번 종류 동물에 대한확률 
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 => 1 번 
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률 
# ....
# w1x1 + w2x2 + ... w7x7 + b => softmax => 0번 종류의 동물에 대한 확률  => 6번 
# 1000000, 0100000,... => [None, 7]

In [37]:
# tf ) ohe 함수 따로 존재
y_one_hot=tf.one_hot(y, 7) # 동물번호 : 3 -> 0001000 < ohe >
print('one_hot', y_one_hot)
y_one_hot=tf.reshape(y_one_hot, [-1,7])
print('one_hot after reshape', y_one_hot)
# ohe hot 함수는 한 차원 높게 변환됨 
# y : [[0],[3], .... [5]]] => [None,1] shape
# one_hot = > [[[1000000]], [[0001000],,,,[00000100]]] => [None, 1, 7]
# 우리가 바라는 출력 결과의 모습은 ( shape ) = [None,7]
# reshape을 하면됨 tf.shape(y_one_hot, [-1,7 ]) 코딩하면 
# [None, 7] 로 reshape됨
# [[[1000000]], [[001]]]


one_hot Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
one_hot after reshape Tensor("Reshape:0", shape=(?, 7), dtype=float32)


In [38]:
w=tf.Variable(tf.random_normal([16, 7]))
b=tf.Variable(tf.random_normal([7]))
#x:[None,16], w:[16,7]
logit= tf.matmul(x,w)+b
hf=tf.nn.softmax(logit)
cost=tf.nn.softmax_cross_entropy_with_logits(logits=logit,
                                             labels=y_one_hot)
cost2=tf.reduce_mean(cost)
train=tf.train.GradientDescentOptimizer(0.1).minimize(cost2)
prediction=tf.argmax(hf,1)
correct_prediction= tf.equal(prediction,tf.argmax(y_one_hot,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


W0805 20:47:36.917624 10632 deprecation.py:323] From <ipython-input-38-e1719c6117b8>:7: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [39]:
# with tf.Session() as sess:
#         sess.run(tf.global_variables_initializer())

#         for step in range(10001):
             
#             sess.run(train, feed_dict = {x:xdata, y:ydata})
#             if step % 100 == 0:
#                 cv = sess.run([cost, hf, train], feed_dict = {x:xdata, y:ydata})
#                     print('step:', step, 'cost:',cv)

In [40]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x:xdata, y:ydata})
        if step % 100==0:
            cv, av=sess.run([cost2, accuracy], feed_dict={x:xdata, y:ydata})
            print("step:", step, "cost:",cv, "acc:", av)
#전체 데이터로 트레이닝 수행하여 모델 생성
#모델에 전체 데이터를 집어 넣어서 정확도 출력
#데이터를 분할하지 않았음
    pred=sess.run(prediction, feed_dict={x:xdata})
    for p,y in zip(pred, ydata.flatten()):
        print('[{}] 예측: {} 실제 y:{}'.format(p==int(y), p, int(y)))
            
#     print(pred)


step: 0 cost: 3.75638 acc: 0.18811882
step: 100 cost: 0.3938743 acc: 0.9009901
step: 200 cost: 0.26423106 acc: 0.9306931
step: 300 cost: 0.20305699 acc: 0.9405941
step: 400 cost: 0.1663855 acc: 0.97029704
step: 500 cost: 0.14149548 acc: 0.97029704
step: 600 cost: 0.123298384 acc: 0.97029704
step: 700 cost: 0.10934756 acc: 0.990099
step: 800 cost: 0.09829734 acc: 0.990099
step: 900 cost: 0.08932926 acc: 1.0
step: 1000 cost: 0.081908755 acc: 1.0
step: 1100 cost: 0.075669296 acc: 1.0
step: 1200 cost: 0.070350565 acc: 1.0
step: 1300 cost: 0.06576266 acc: 1.0
step: 1400 cost: 0.061763994 acc: 1.0
step: 1500 cost: 0.05824719 acc: 1.0
step: 1600 cost: 0.055129193 acc: 1.0
step: 1700 cost: 0.052345023 acc: 1.0
step: 1800 cost: 0.049843118 acc: 1.0
step: 1900 cost: 0.047581997 acc: 1.0
step: 2000 cost: 0.045527946 acc: 1.0
step: 2100 cost: 0.043653365 acc: 1.0
step: 2200 cost: 0.041935235 acc: 1.0
step: 2300 cost: 0.040354434 acc: 1.0
step: 2400 cost: 0.038894854 acc: 1.0
step: 2500 cost: 0.037

In [41]:
# zip 함수 : 끼리끼리 묶어주는 함수 
# flatten 
# [[1],[0]] => [1,0]
