In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder


In [2]:
data=np.array([[0,1,1],
              [0,2,2],
              [1,0,3],
              [1,1,4],
              [0,0,0],
              ])
data

array([[0, 1, 1],
       [0, 2, 2],
       [1, 0, 3],
       [1, 1, 4],
       [0, 0, 0]])

In [3]:
ohe = OneHotEncoder()
ohe.fit(data)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [4]:
ohe.active_features_


C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function active_features_ is deprecated; The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [5]:

ohe.n_values_

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function n_values_ is deprecated; The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([2, 3, 5])

In [6]:
ohe.feature_indices_

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function feature_indices_ is deprecated; The ``feature_indices_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([ 0,  2,  5, 10], dtype=int32)

In [8]:
test=np.array([[0,1,3]])
test

array([[0, 1, 3]])

In [9]:
ohe.transform(test).toarray()

array([[1., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [10]:
test

array([[0, 1, 3]])

In [11]:
from pandas import DataFrame
np.random.seed()
df=DataFrame({
    'd1':np.random.randn(10),
    'd2':['x','x','x','x','x','y','y','y','y','y']
})
df

d1 d2
0  0.397673  x
1  0.211869  x
2  0.667043  x
3 -1.839743  x
4 -0.168008  x
5  0.065879  y
6 -2.470697  y
7  3.770576  y
8  2.359721  y
9 -1.004242  y

In [12]:
df[['d1']]
type(df)
bins=np.linspace(df.d1.min(), df.d1.max(), 5)
df['d1_bin']=np.digitize(df['d1'], bins)
df
# 전체 최소 최대값구간에 거쳐 5등분을 하고 이에 따른 순서 범주화를 한후 이에따른 순서도출

d1 d2  d1_bin
0  0.397673  x       2
1  0.211869  x       2
2  0.667043  x       3
3 -1.839743  x       1
4 -0.168008  x       2
5  0.065879  y       2
6 -2.470697  y       1
7  3.770576  y       5
8  2.359721  y       4
9 -1.004242  y       1

In [15]:
bins=np.linspace(df.d1.min(), df.d1.max(),5)
bins

array([-2.47069719, -0.91037892,  0.64993934,  2.2102576 ,  3.77057586])

In [17]:
df['d1_bin']=np.digitize(df['d1'], bins)
df['d1_bin']

0    2
1    2
2    3
3    1
4    2
5    2
6    1
7    5
8    4
9    1
Name: d1_bin, dtype: int64

In [18]:
df.groupby('d1_bin')['d1'].size()


d1_bin
1    3
2    4
3    1
4    1
5    1
Name: d1, dtype: int64

In [19]:
df.groupby('d1_bin')['d1'].mean()

d1_bin
1   -1.771561
2    0.126853
3    0.667043
4    2.359721
5    3.770576
Name: d1, dtype: float64

In [20]:
df.groupby('d1_bin')['d1'].sum()

d1_bin
1   -5.314682
2    0.507412
3    0.667043
4    2.359721
5    3.770576
Name: d1, dtype: float64

In [22]:
df.groupby('d1_bin')['d1'].std()

d1_bin
1    0.735601
2    0.238909
3         NaN
4         NaN
5         NaN
Name: d1, dtype: float64

In [23]:
df.groupby('d1_bin')['d2'].value_counts()

d1_bin  d2
1       y     2
        x     1
2       x     3
        y     1
3       x     1
4       y     1
5       y     1
Name: d2, dtype: int64

In [24]:
df['d1_bin']==3

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: d1_bin, dtype: bool

In [25]:
df['d1'].mean()

0.1990069435977471

In [26]:
df['hl']=np.where(df['d1']>=df['d1'].mean(), 'high', 'low')
df

d1 d2  d1_bin    hl
0  0.397673  x       2  high
1  0.211869  x       2  high
2  0.667043  x       3  high
3 -1.839743  x       1   low
4 -0.168008  x       2   low
5  0.065879  y       2   low
6 -2.470697  y       1   low
7  3.770576  y       5  high
8  2.359721  y       4  high
9 -1.004242  y       1   low

In [28]:
df.groupby('hl')['d1'].size()


hl
high    5
low     5
Name: d1, dtype: int64

In [29]:
df.groupby('hl')['d1'].mean()

hl
high    1.481376
low    -1.083362
Name: d1, dtype: float64

In [30]:
df.groupby('hl')['d1'].std()

hl
high    1.537947
low     1.079548
Name: d1, dtype: float64

In [31]:
df['d1']

0    0.397673
1    0.211869
2    0.667043
3   -1.839743
4   -0.168008
5    0.065879
6   -2.470697
7    3.770576
8    2.359721
9   -1.004242
Name: d1, dtype: float64

In [32]:
Q1=np.percentile(df['d1'],25)
Q1

-0.7951837542880769

In [33]:
Q3=np.percentile(df['d1'],75)
Q3

0.5997004519870395

In [34]:
df['hml']=np.where(df['d1']>=Q3, 'high',
                  np.where(df['d1']>=Q1, 'medium',
                          'low'))
df['hml']

0    medium
1    medium
2      high
3       low
4    medium
5    medium
6       low
7      high
8      high
9       low
Name: hml, dtype: object

In [35]:
data=np.arange(6).reshape(3,2)
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()
poly.fit_transform(data)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [44]:
df=DataFrame({
    'c_id':['c1','c1','c1','c2','c2','c2','c3','c3','c3'],
    'p_id':['p1','p1','p1','p2','p2','p2','p3','p3','p3'],
    'amount':[20,10,0,30,20,30,0,5,10],
    'reg':['S','S','S','S','S','S','A','A','A']
})
df

c_id p_id  amount reg
0   c1   p1      20   S
1   c1   p1      10   S
2   c1   p1       0   S
3   c2   p2      30   S
4   c2   p2      20   S
5   c2   p2      30   S
6   c3   p3       0   A
7   c3   p3       5   A
8   c3   p3      10   A

In [48]:
# df.pivot(index='c_id', columns='p_id', values='amount')

In [49]:
df.pivot_table(index='p_id', columns='c_id', values='amount')

c_id    c1         c2   c3
p_id                      
p1    10.0        NaN  NaN
p2     NaN  26.666667  NaN
p3     NaN        NaN  5.0

In [50]:
df.pivot_table(index=['c_id','reg'], columns='p_id', values='amount')

p_id        p1         p2   p3
c_id reg                      
c1   S    10.0        NaN  NaN
c2   S     NaN  26.666667  NaN
c3   A     NaN        NaN  5.0

In [52]:
df.pivot_table(index=['reg'], columns='p_id', values='amount', aggfunc=np.sum)

p_id    p1    p2    p3
reg                   
A      NaN   NaN  15.0
S     30.0  80.0   NaN

In [53]:
df1=pd.read_csv('data/concat_1.csv')
df1

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [54]:
df2=pd.read_csv('data/concat_2.csv')
df2

A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [56]:
row_concat=pd.concat([df1,df2])
row_concat

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [58]:
raw_concat=pd.concat([df1,df2],axis=1)
raw_concat

A   B   C   D   A   B   C   D
0  a0  b0  c0  d0  a4  b4  c4  d4
1  a1  b1  c1  d1  a5  b5  c5  d5
2  a2  b2  c2  d2  a6  b6  c6  d6
3  a3  b3  c3  d3  a7  b7  c7  d7

In [59]:
row_concat.iloc[3,]


A    a3
B    b3
C    c3
D    d3
Name: 3, dtype: object

In [61]:
row_concat.iloc[:3]

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2

In [62]:
row_concat.iloc[2:7]

A   B   C   D
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6

In [63]:
new_row_series=pd.Series(['n1','n2','n3','n4'])
new_row_series

0    n1
1    n2
2    n3
3    n4
dtype: object

In [64]:
pd.concat([df1, new_row_series])

A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

In [65]:
new_row_df=pd.DataFrame([['n1','n2','n3','n4']], columns=['A','B','C','D'])
pd.concat([df1, new_row_df])

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  n1  n2  n3  n4

In [68]:
data_dict={'A':'N1','B':'N2','C':'N3','D':'N4'}
df1.append(data_dict, ignore_index=True)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  N1  N2  N3  N4

In [74]:
mi=pd.MultiIndex.from_tuples([('c1','2019'),('c1','2020'),('c2','2019'),('c2','2020')])
mi


MultiIndex(levels=[['c1', 'c2'], ['2019', '2020']],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [75]:
df = DataFrame(np.arange(16).reshape(4,4),
              index=mi,
              columns=['p1','p2','p3','p4'])
df

p1  p2  p3  p4
c1 2019   0   1   2   3
   2020   4   5   6   7
c2 2019   8   9  10  11
   2020  12  13  14  15

In [76]:
ds=df.stack()
ds

c1  2019  p1     0
          p2     1
          p3     2
          p4     3
    2020  p1     4
          p2     5
          p3     6
          p4     7
c2  2019  p1     8
          p2     9
          p3    10
          p4    11
    2020  p1    12
          p2    13
          p3    14
          p4    15
dtype: int32

In [77]:
type(ds)

pandas.core.series.Series

In [78]:
ds.index

MultiIndex(levels=[['c1', 'c2'], ['2019', '2020'], ['p1', 'p2', 'p3', 'p4']],
           codes=[[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]])

In [ ]:
ds.index